### PR TITLE
Introduce slack notifier

### PR DESCRIPTION
**Pull request by udzura**
It may be useful when we live in Slack!

### CODE REVIEW

**Comment by udzura** [comment]
Notification will be like this:

**Comment by udzura** [comment]
Now using https://github.com/linyows/breacan thanks @linyows !!!!!!!

**Comment by mizoR** [comment]
Thanks. LGTM :+1:

**Comment by udzura** [comment]
:congratulations:

**Comment by linyows** [comment]
:100:

**Pull request merged**
