### PR TITLE
Add notice option to slack adapter

### PR DESCRIPTION
**Pull request by udzura**
Hi, @mizoR 

I've added `notice_when_fail` option to Slack notifier.

Also, I've added some message tests.

### CODE REVIEW

**Comment by mizoR** [comment]
Thank you, looks good :+1:

**Comment by mizoR** [comment]
It's released as 0.0.4 :santa:

**Comment by udzura** [comment]
Thanks! :santa:

**Comment by udzura** [comment]
Wow, RAILS_ENV in message should be `test` in CI. Sorry...

**Comment by mizoR** [comment]
> RAILS_ENV in message should be test 

It was fixed at https://github.com/mizoR/rake_notification/pull/11, thanks :octocat:

**Pull request merged**
